app:
  api:
    github-base-url: https://api.github.com
    stackoverflow-base-url: https://api.stackexchange.com
    bot-base-url: http://localhost:8090
  scheduler:
    enable: false
    interval: 30s
    force-check-delay: 60s
  data-access-type: jpa

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: scrapper
  liquibase:
    enabled: false
  jooq:
    sql-dialect: POSTGRES
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        physical_naming_strategy: edu.eflerrr.scrapper.configuration.hibernate.CustomPhysicalNamingStrategy
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
