app:
  api:
    github-base-url: https://api.github.com
    stackoverflow-base-url: https://api.stackexchange.com
    bot-base-url: localhost:8090
  scheduler:
    enable: true
    interval: 5s
    force-check-delay: 15s
  service:
    implementation: jdbc

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: scrapper
  liquibase:
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
