app:
  api:
    github-base-url: https://api.github.com
    stackoverflow-base-url: https://api.stackexchange.com
    bot-base-url: localhost:8090
  scheduler:
    enable: true
    interval: 5s
    force-check-delay: 10s

spring:
  application:
    name: scrapper

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
