app:
  telegram-token: ${token}
  available-sites:
    - github.com
    - stackoverflow.com
  api:
    scrapper-base-url: http://localhost:8080
  retry:
    scrapper-client:
      enable: true
      retry-status-codes:
        - 500
      backoff-policy: constant
      max-attempts: -1
      initial-interval: 2s
      multiplier: 2.0

spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
  application:
    name: bot
  jackson:
    time-zone: UTC
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      rate-limits:
        - cache-key: "@securityService.getClientIP(#this)"
          bandwidths:
            - capacity: 5
              time: 60
              unit: seconds

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
