app:
  telegram-token: ${token}
  available-sites:
    - github.com
    - stackoverflow.com
  add-queue: true
  ignore-income-updates: false
  api:
    scrapper-base-url: http://localhost:8080
  kafka:
    bootstrap-servers: localhost:9093
    topic:
      name: updates
    consumer:
      client-id: bot
      group-id: telegram-bots
      auto-offset-reset: latest
    dlq:
      dlq-topic-name: updates-dlq
      backoff-interval: 1000
      backoff-max-attempts: 2
  retry:
    scrapper-client:
      enable: true
      retry-status-codes:
        - 500
      backoff-policy: linear
      max-attempts: -1
      initial-interval: 2s
      multiplier: 2.0

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

management:
  server:
    port: 12090
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - info
          - health
          - prometheus
      path-mapping:
        prometheus: metrics
  metrics:
    tags:
      application: ${spring.application.name}
