/*
 * This file is generated by jOOQ.
 */

package edu.eflerrr.scrapper.domain.jooq;

import edu.eflerrr.scrapper.domain.jooq.tables.Branch;
import edu.eflerrr.scrapper.domain.jooq.tables.Chat;
import edu.eflerrr.scrapper.domain.jooq.tables.Link;
import edu.eflerrr.scrapper.domain.jooq.tables.Tracking;
import edu.eflerrr.scrapper.domain.jooq.tables.records.BranchRecord;
import edu.eflerrr.scrapper.domain.jooq.tables.records.ChatRecord;
import edu.eflerrr.scrapper.domain.jooq.tables.records.LinkRecord;
import edu.eflerrr.scrapper.domain.jooq.tables.records.TrackingRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BranchRecord> CONSTRAINT_7 =
        Internal.createUniqueKey(Branch.BRANCH, DSL.name("CONSTRAINT_7"), new TableField[] {Branch.BRANCH.ID}, true);
    public static final UniqueKey<ChatRecord> CONSTRAINT_2 =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_2"), new TableField[] {Chat.CHAT.ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_24 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_24"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_242 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_242"), new TableField[] {Link.LINK.URL}, true);
    public static final UniqueKey<TrackingRecord> CONSTRAINT_4 = Internal.createUniqueKey(Tracking.TRACKING,
        DSL.name("CONSTRAINT_4"),
        new TableField[] {Tracking.TRACKING.ID},
        true
    );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TrackingRecord, ChatRecord> CONSTRAINT_4F =
        Internal.createForeignKey(Tracking.TRACKING,
            DSL.name("CONSTRAINT_4F"),
            new TableField[] {Tracking.TRACKING.CHAT_ID},
            Keys.CONSTRAINT_2,
            new TableField[] {Chat.CHAT.ID},
            true
        );
    public static final ForeignKey<TrackingRecord, LinkRecord> CONSTRAINT_4F9 =
        Internal.createForeignKey(Tracking.TRACKING,
            DSL.name("CONSTRAINT_4F9"),
            new TableField[] {Tracking.TRACKING.LINK_ID},
            Keys.CONSTRAINT_24,
            new TableField[] {Link.LINK.ID},
            true
        );
}
